// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern void ui_event_LightBlue(lv_event_t * e);
extern lv_obj_t * ui_LightBlue;
extern void ui_event_BulbBlue(lv_event_t * e);
extern lv_obj_t * ui_BulbBlue;
extern void ui_event_volumeBlue(lv_event_t * e);
extern lv_obj_t * ui_volumeBlue;
extern lv_obj_t * ui_s1select;
extern lv_obj_t * ui_volumeWhite;
extern lv_obj_t * ui_LightWhite;
extern lv_obj_t * ui_BulbWhite;
extern lv_obj_t * ui_volumeTextWhite;
extern lv_obj_t * ui_volumeTextBlue;
extern lv_obj_t * ui_LightTextBlue;
extern lv_obj_t * ui_LightTextWhite;
extern lv_obj_t * ui_BulbTextWhite;
extern lv_obj_t * ui_BulbTextBlue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

