// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_VolumeArc;
extern void ui_event_screen2ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen2ReturnBt;
extern lv_obj_t * ui_VolumeReturnLabel;
extern lv_obj_t * ui_VolumeImage;
extern lv_obj_t * ui_VolNum;
extern lv_obj_t * ui_VolumeLabel;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

