// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: 1_69_round_display

#ifndef _1_69_ROUND_DISPLAY_UI_H
#define _1_69_ROUND_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void progress_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
extern lv_obj_t * ui_Screen0;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_progress;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_LightBlue(lv_event_t * e);
extern lv_obj_t * ui_LightBlue;
void ui_event_BulbBlue(lv_event_t * e);
extern lv_obj_t * ui_BulbBlue;
void ui_event_volumeBlue(lv_event_t * e);
extern lv_obj_t * ui_volumeBlue;
extern lv_obj_t * ui_s1select;
extern lv_obj_t * ui_volumeWhite;
extern lv_obj_t * ui_LightWhite;
extern lv_obj_t * ui_BulbWhite;
extern lv_obj_t * ui_volumeTextWhite;
extern lv_obj_t * ui_volumeTextBlue;
extern lv_obj_t * ui_LightTextBlue;
extern lv_obj_t * ui_LightTextWhite;
extern lv_obj_t * ui_BulbTextWhite;
extern lv_obj_t * ui_BulbTextBlue;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_VolumeArc;
void ui_event_screen2ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen2ReturnBt;
extern lv_obj_t * ui_VolumeReturnLabel;
extern lv_obj_t * ui_VolumeImage;
extern lv_obj_t * ui_VolNum;
extern lv_obj_t * ui_VolumeLabel;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_BulbArc;
void ui_event_screen3ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen3ReturnBt;
extern lv_obj_t * ui_BulbReturnLabel;
extern lv_obj_t * ui_BulbNum;
extern lv_obj_t * ui_BulbLabel;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_BulbImage;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_LightArc;
void ui_event_screen4RerutnBt(lv_event_t * e);
extern lv_obj_t * ui_screen4RerutnBt;
extern lv_obj_t * ui_LightReturnLabel;
extern lv_obj_t * ui_LightNum;
extern lv_obj_t * ui_LightLabel;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_LightImage;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_950378288);    // assets/power_on_light_400_250707@2x.png
LV_IMG_DECLARE(ui_img_127450014);    // assets/power_on_progress_01@2x(1).png
LV_IMG_DECLARE(ui_img_360_1_png);    // assets/360_1.png
LV_IMG_DECLARE(ui_img_screen_brightness_45_bule_png);    // assets/screen_brightness_45_bule.png
LV_IMG_DECLARE(ui_img_667923968);    // assets/icon_light_602@2x.png
LV_IMG_DECLARE(ui_img_1854458106);    // assets/icon_volume_602@2x.png
LV_IMG_DECLARE(ui_img_icon_140x400_02_png);    // assets/icon_140x400_02.png
LV_IMG_DECLARE(ui_img_247194651);    // assets/icon_volume_40@3x.png
LV_IMG_DECLARE(ui_img_screen_brightness_45_white_png);    // assets/screen_brightness_45_white.png
LV_IMG_DECLARE(ui_img_32356014);    // assets/icon_light_601@3x(1).png
LV_IMG_DECLARE(ui_img_1761703117);    // assets/v2_bj_volume_100@2x.png
LV_IMG_DECLARE(ui_img_bar_white_png);    // assets/bar_white.png
LV_IMG_DECLARE(ui_img_bar_bule_png);    // assets/bar_bule.png
LV_IMG_DECLARE(ui_img_360_bg_png);    // assets/360_bg.png
LV_IMG_DECLARE(ui_img_bar_orange_02_png);    // assets/bar_orange_02.png
LV_IMG_DECLARE(ui_img_1741863219);    // assets/v2_bj_light_100@2x.png
LV_IMG_DECLARE(ui_img_bar_yellow_02_png);    // assets/bar_yellow_02.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
