// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: 1_69_round_display

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen3, &ui_img_360_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbArc = lv_arc_create(ui_Screen3);
    lv_obj_set_width(ui_BulbArc, 252);
    lv_obj_set_height(ui_BulbArc, 252);
    lv_obj_set_x(ui_BulbArc, 1);
    lv_obj_set_y(ui_BulbArc, 1);
    lv_obj_set_align(ui_BulbArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_BulbArc, 0, 200);
    lv_arc_set_value(ui_BulbArc, 1);
    lv_obj_set_style_arc_width(ui_BulbArc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BulbArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_BulbArc, &ui_img_bar_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_BulbArc, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BulbArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_BulbArc, &ui_img_bar_orange_02_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BulbArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BulbArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_screen3ReturnBt = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_screen3ReturnBt, 80);
    lv_obj_set_height(ui_screen3ReturnBt, 40);
    lv_obj_set_x(ui_screen3ReturnBt, 0);
    lv_obj_set_y(ui_screen3ReturnBt, 110);
    lv_obj_set_align(ui_screen3ReturnBt, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_screen3ReturnBt, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen3ReturnBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_screen3ReturnBt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_screen3ReturnBt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbReturnLabel = lv_label_create(ui_screen3ReturnBt);
    lv_obj_set_width(ui_BulbReturnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BulbReturnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BulbReturnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BulbReturnLabel, "Return");
    lv_obj_set_style_text_color(ui_BulbReturnLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BulbReturnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbNum = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_BulbNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BulbNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BulbNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BulbNum, "50%");
    lv_obj_set_style_text_color(ui_BulbNum, lv_color_hex(0xFF9F1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BulbNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BulbNum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_BulbLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BulbLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BulbLabel, 0);
    lv_obj_set_y(ui_BulbLabel, 50);
    lv_obj_set_align(ui_BulbLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BulbLabel, "Bulb");
    lv_obj_set_style_text_color(ui_BulbLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BulbLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BulbLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button7, 36);
    lv_obj_set_height(ui_Button7, 210);
    lv_obj_set_x(ui_Button7, -60);
    lv_obj_set_y(ui_Button7, 55);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button11, 36);
    lv_obj_set_height(ui_Button11, 210);
    lv_obj_set_x(ui_Button11, 60);
    lv_obj_set_y(ui_Button11, 55);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button18 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button18, 80);
    lv_obj_set_height(ui_Button18, 50);
    lv_obj_set_x(ui_Button18, 0);
    lv_obj_set_y(ui_Button18, 63);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button9, 80);
    lv_obj_set_height(ui_Button9, 40);
    lv_obj_set_x(ui_Button9, 0);
    lv_obj_set_y(ui_Button9, 153);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button8, 70);
    lv_obj_set_height(ui_Button8, 70);
    lv_obj_set_x(ui_Button8, -77);
    lv_obj_set_y(ui_Button8, 130);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button10, 70);
    lv_obj_set_height(ui_Button10, 70);
    lv_obj_set_x(ui_Button10, 77);
    lv_obj_set_y(ui_Button10, 130);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbImage = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_BulbImage, &ui_img_32356014);
    lv_obj_set_width(ui_BulbImage, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_BulbImage, LV_SIZE_CONTENT);    /// 47
    lv_obj_set_x(ui_BulbImage, 0);
    lv_obj_set_y(ui_BulbImage, -70);
    lv_obj_set_align(ui_BulbImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BulbImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BulbImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_screen3ReturnBt, ui_event_screen3ReturnBt, LV_EVENT_ALL, NULL);

}
