// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#ifndef _1_46_ROUND_DISPLAY_UI_H
#define _1_46_ROUND_DISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen0.h"
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * progress_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMAGE_DECLARE(ui_img_950378288);    // assets/power_on_light_400_250707@2x.png
LV_IMAGE_DECLARE(ui_img_127450014);    // assets/power_on_progress_01@2x(1).png
LV_IMAGE_DECLARE(ui_img_360_1_png);    // assets/360_1.png
LV_IMAGE_DECLARE(ui_img_screen_brightness_45_bule_png);    // assets/screen_brightness_45_bule.png
LV_IMAGE_DECLARE(ui_img_667923968);    // assets/icon_light_602@2x.png
LV_IMAGE_DECLARE(ui_img_1854458106);    // assets/icon_volume_602@2x.png
LV_IMAGE_DECLARE(ui_img_icon_140x400_02_png);    // assets/icon_140x400_02.png
LV_IMAGE_DECLARE(ui_img_247194651);    // assets/icon_volume_40@3x.png
LV_IMAGE_DECLARE(ui_img_screen_brightness_45_white_png);    // assets/screen_brightness_45_white.png
LV_IMAGE_DECLARE(ui_img_32356014);    // assets/icon_light_601@3x(1).png
LV_IMAGE_DECLARE(ui_img_1761703117);    // assets/v2_bj_volume_100@2x.png
LV_IMAGE_DECLARE(ui_img_bar_white_png);    // assets/bar_white.png
LV_IMAGE_DECLARE(ui_img_bar_bule_png);    // assets/bar_bule.png
LV_IMAGE_DECLARE(ui_img_360_bg_png);    // assets/360_bg.png
LV_IMAGE_DECLARE(ui_img_bar_orange_02_png);    // assets/bar_orange_02.png
LV_IMAGE_DECLARE(ui_img_1741863219);    // assets/v2_bj_light_100@2x.png
LV_IMAGE_DECLARE(ui_img_bar_yellow_02_png);    // assets/bar_yellow_02.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
