// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#include "ui.h"

lv_obj_t * ui_Screen0 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_progress = NULL;
// event funtions
void ui_event_Screen0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        progress_Animation(ui_progress, 0);
    }
}

// build funtions

void ui_Screen0_screen_init(void)
{
    ui_Screen0 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Screen0);
    lv_image_set_src(ui_Image4, &ui_img_950378288);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 300
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_progress = lv_image_create(ui_Screen0);
    lv_image_set_src(ui_progress, &ui_img_127450014);
    lv_obj_set_width(ui_progress, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_progress, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_align(ui_progress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_progress, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_progress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen0, ui_event_Screen0, LV_EVENT_ALL, NULL);

}

void ui_Screen0_screen_destroy(void)
{
    if(ui_Screen0) lv_obj_delete(ui_Screen0);

    // NULL screen variables
    ui_Screen0 = NULL;
    ui_Image4 = NULL;
    ui_progress = NULL;

}
