// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_VolumeArc = NULL;
lv_obj_t * ui_screen2ReturnBt = NULL;
lv_obj_t * ui_VolumeReturnLabel = NULL;
lv_obj_t * ui_VolumeImage = NULL;
lv_obj_t * ui_VolNum = NULL;
lv_obj_t * ui_VolumeLabel = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button5 = NULL;
// event funtions
void ui_event_screen2ReturnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen2, &ui_img_1761703117, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeArc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_VolumeArc, 250);
    lv_obj_set_height(ui_VolumeArc, 250);
    lv_obj_set_align(ui_VolumeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_VolumeArc, 50);
    lv_obj_set_style_arc_width(ui_VolumeArc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_VolumeArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_VolumeArc, &ui_img_bar_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_VolumeArc, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_VolumeArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_VolumeArc, &ui_img_bar_bule_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_screen2ReturnBt = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_screen2ReturnBt, 80);
    lv_obj_set_height(ui_screen2ReturnBt, 40);
    lv_obj_set_x(ui_screen2ReturnBt, 0);
    lv_obj_set_y(ui_screen2ReturnBt, 110);
    lv_obj_set_align(ui_screen2ReturnBt, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_screen2ReturnBt, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen2ReturnBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_screen2ReturnBt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_screen2ReturnBt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeReturnLabel = lv_label_create(ui_screen2ReturnBt);
    lv_obj_set_width(ui_VolumeReturnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumeReturnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VolumeReturnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeReturnLabel, "Return");
    lv_obj_set_style_text_color(ui_VolumeReturnLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeReturnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeImage = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_VolumeImage, &ui_img_247194651);
    lv_obj_set_width(ui_VolumeImage, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_VolumeImage, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_VolumeImage, 0);
    lv_obj_set_y(ui_VolumeImage, -70);
    lv_obj_set_align(ui_VolumeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VolumeImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_VolumeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VolNum = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VolNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VolNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolNum, "50%");
    lv_obj_set_style_text_color(ui_VolNum, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolNum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VolumeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolumeLabel, 0);
    lv_obj_set_y(ui_VolumeLabel, 50);
    lv_obj_set_align(ui_VolumeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumeLabel, "Volume");
    lv_obj_set_style_text_color(ui_VolumeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 36);
    lv_obj_set_height(ui_Button1, 210);
    lv_obj_set_x(ui_Button1, -60);
    lv_obj_set_y(ui_Button1, 55);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button2, 36);
    lv_obj_set_height(ui_Button2, 210);
    lv_obj_set_x(ui_Button2, 60);
    lv_obj_set_y(ui_Button2, 55);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 80);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 63);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button3, 80);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, 153);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button6, 70);
    lv_obj_set_height(ui_Button6, 70);
    lv_obj_set_x(ui_Button6, -77);
    lv_obj_set_y(ui_Button6, 130);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button5, 70);
    lv_obj_set_height(ui_Button5, 70);
    lv_obj_set_x(ui_Button5, 77);
    lv_obj_set_y(ui_Button5, 130);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen2ReturnBt, ui_event_screen2ReturnBt, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_delete(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_VolumeArc = NULL;
    ui_screen2ReturnBt = NULL;
    ui_VolumeReturnLabel = NULL;
    ui_VolumeImage = NULL;
    ui_VolNum = NULL;
    ui_VolumeLabel = NULL;
    ui_Button1 = NULL;
    ui_Button2 = NULL;
    ui_Button4 = NULL;
    ui_Button3 = NULL;
    ui_Button6 = NULL;
    ui_Button5 = NULL;

}
