// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_LightArc = NULL;
lv_obj_t * ui_screen4RerutnBt = NULL;
lv_obj_t * ui_LightReturnLabel = NULL;
lv_obj_t * ui_LightNum = NULL;
lv_obj_t * ui_LightLabel = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Button19 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Button17 = NULL;
lv_obj_t * ui_LightImage = NULL;
// event funtions
void ui_event_screen4RerutnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCREEN_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Screen4, &ui_img_1741863219, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightArc = lv_arc_create(ui_Screen4);
    lv_obj_set_width(ui_LightArc, 256);
    lv_obj_set_height(ui_LightArc, 256);
    lv_obj_set_align(ui_LightArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_LightArc, 100);
    lv_obj_set_style_arc_width(ui_LightArc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LightArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_LightArc, &ui_img_bar_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_LightArc, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LightArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_LightArc, &ui_img_bar_yellow_02_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_screen4RerutnBt = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_screen4RerutnBt, 80);
    lv_obj_set_height(ui_screen4RerutnBt, 40);
    lv_obj_set_x(ui_screen4RerutnBt, 0);
    lv_obj_set_y(ui_screen4RerutnBt, 110);
    lv_obj_set_align(ui_screen4RerutnBt, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_screen4RerutnBt, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen4RerutnBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_screen4RerutnBt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_screen4RerutnBt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightReturnLabel = lv_label_create(ui_screen4RerutnBt);
    lv_obj_set_width(ui_LightReturnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightReturnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LightReturnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightReturnLabel, "Return");
    lv_obj_set_style_text_color(ui_LightReturnLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightReturnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightNum = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LightNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LightNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightNum, "50%");
    lv_obj_set_style_text_color(ui_LightNum, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightNum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabel = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLabel, 0);
    lv_obj_set_y(ui_LightLabel, 50);
    lv_obj_set_align(ui_LightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabel, "Light");
    lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button15, 36);
    lv_obj_set_height(ui_Button15, 210);
    lv_obj_set_x(ui_Button15, -60);
    lv_obj_set_y(ui_Button15, 55);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button16, 36);
    lv_obj_set_height(ui_Button16, 210);
    lv_obj_set_x(ui_Button16, 60);
    lv_obj_set_y(ui_Button16, 55);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button19, 80);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, 0);
    lv_obj_set_y(ui_Button19, 62);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button13, 80);
    lv_obj_set_height(ui_Button13, 40);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, 153);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button14, 70);
    lv_obj_set_height(ui_Button14, 70);
    lv_obj_set_x(ui_Button14, -77);
    lv_obj_set_y(ui_Button14, 130);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_button_create(ui_Screen4);
    lv_obj_set_width(ui_Button17, 70);
    lv_obj_set_height(ui_Button17, 70);
    lv_obj_set_x(ui_Button17, 77);
    lv_obj_set_y(ui_Button17, 130);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightImage = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_LightImage, &ui_img_screen_brightness_45_white_png);
    lv_obj_set_width(ui_LightImage, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_LightImage, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_LightImage, 0);
    lv_obj_set_y(ui_LightImage, -70);
    lv_obj_set_align(ui_LightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_LightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_screen4RerutnBt, ui_event_screen4RerutnBt, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_delete(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_LightArc = NULL;
    ui_screen4RerutnBt = NULL;
    ui_LightReturnLabel = NULL;
    ui_LightNum = NULL;
    ui_LightLabel = NULL;
    ui_Button15 = NULL;
    ui_Button16 = NULL;
    ui_Button19 = NULL;
    ui_Button13 = NULL;
    ui_Button14 = NULL;
    ui_Button17 = NULL;
    ui_LightImage = NULL;

}
