SET(SOURCES ui_Screen0.c
    ui_Screen1.c
    ui_Screen2.c
    ui_Screen3.c
    ui_Screen4.c
    ui.c
    ui_comp_hook.c
    ui_helpers.c
    ui_img_950378288.c
    ui_img_127450014.c
    ui_img_360_1_png.c
    ui_img_screen_brightness_45_bule_png.c
    ui_img_667923968.c
    ui_img_1854458106.c
    ui_img_icon_140x400_02_png.c
    ui_img_247194651.c
    ui_img_screen_brightness_45_white_png.c
    ui_img_32356014.c
    ui_img_1761703117.c
    ui_img_bar_white_png.c
    ui_img_bar_bule_png.c
    ui_img_360_bg_png.c
    ui_img_bar_orange_02_png.c
    ui_img_1741863219.c
    ui_img_bar_yellow_02_png.c)

add_library(ui ${SOURCES})
