// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: 1_69_round_display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void progress_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen0
void ui_Screen0_screen_init(void);
void ui_event_Screen0(lv_event_t * e);
lv_obj_t * ui_Screen0;
lv_obj_t * ui_Image4;
lv_obj_t * ui_progress;
// CUSTOM VARIABLES

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_LightBlue(lv_event_t * e);
lv_obj_t * ui_LightBlue;
void ui_event_BulbBlue(lv_event_t * e);
lv_obj_t * ui_BulbBlue;
void ui_event_volumeBlue(lv_event_t * e);
lv_obj_t * ui_volumeBlue;
lv_obj_t * ui_s1select;
lv_obj_t * ui_volumeWhite;
lv_obj_t * ui_LightWhite;
lv_obj_t * ui_BulbWhite;
lv_obj_t * ui_volumeTextWhite;
lv_obj_t * ui_volumeTextBlue;
lv_obj_t * ui_LightTextBlue;
lv_obj_t * ui_LightTextWhite;
lv_obj_t * ui_BulbTextWhite;
lv_obj_t * ui_BulbTextBlue;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_VolumeArc;
void ui_event_screen2ReturnBt(lv_event_t * e);
lv_obj_t * ui_screen2ReturnBt;
lv_obj_t * ui_VolumeReturnLabel;
lv_obj_t * ui_VolumeImage;
lv_obj_t * ui_VolNum;
lv_obj_t * ui_VolumeLabel;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_BulbArc;
void ui_event_screen3ReturnBt(lv_event_t * e);
lv_obj_t * ui_screen3ReturnBt;
lv_obj_t * ui_BulbReturnLabel;
lv_obj_t * ui_BulbNum;
lv_obj_t * ui_BulbLabel;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Button18;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Button10;
lv_obj_t * ui_BulbImage;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_LightArc;
void ui_event_screen4RerutnBt(lv_event_t * e);
lv_obj_t * ui_screen4RerutnBt;
lv_obj_t * ui_LightReturnLabel;
lv_obj_t * ui_LightNum;
lv_obj_t * ui_LightLabel;
lv_obj_t * ui_Button15;
lv_obj_t * ui_Button16;
lv_obj_t * ui_Button19;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Button14;
lv_obj_t * ui_Button17;
lv_obj_t * ui_LightImage;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void progress_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_angle);
    lv_anim_set_values(&PropertyAnimation_0, 0, 3600);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 3);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_angle);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        progress_Animation(ui_progress, 0);
    }
}

void ui_event_LightBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_BulbBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_volumeBlue(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_screen2ReturnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_screen3ReturnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_screen4RerutnBt(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen0_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen0);
}
