// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_BulbArc;
extern void ui_event_screen3ReturnBt(lv_event_t * e);
extern lv_obj_t * ui_screen3ReturnBt;
extern lv_obj_t * ui_BulbReturnLabel;
extern lv_obj_t * ui_BulbNum;
extern lv_obj_t * ui_BulbLabel;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_BulbImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

