// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: 1_69_round_display

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_360_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightBlue = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_LightBlue, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_screen_brightness_45_bule_png, NULL);
    lv_obj_set_width(ui_LightBlue, 45);
    lv_obj_set_height(ui_LightBlue, 45);
    lv_obj_set_align(ui_LightBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_BulbBlue = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_BulbBlue, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_667923968, NULL);
    lv_obj_set_width(ui_BulbBlue, 45);
    lv_obj_set_height(ui_BulbBlue, 45);
    lv_obj_set_align(ui_BulbBlue, LV_ALIGN_CENTER);

    ui_volumeBlue = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_volumeBlue, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1854458106, NULL);
    lv_obj_set_width(ui_volumeBlue, 45);
    lv_obj_set_height(ui_volumeBlue, 45);
    lv_obj_set_align(ui_volumeBlue, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volumeBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_s1select = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_s1select, &ui_img_icon_140x400_02_png);
    lv_obj_set_width(ui_s1select, LV_SIZE_CONTENT);   /// 106
    lv_obj_set_height(ui_s1select, LV_SIZE_CONTENT);    /// 300
    lv_obj_set_align(ui_s1select, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_s1select, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_s1select, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumeWhite = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_volumeWhite, &ui_img_247194651);
    lv_obj_set_width(ui_volumeWhite, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_volumeWhite, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_volumeWhite, -110);
    lv_obj_set_y(ui_volumeWhite, 0);
    lv_obj_set_align(ui_volumeWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_volumeWhite, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volumeWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightWhite = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_LightWhite, &ui_img_screen_brightness_45_white_png);
    lv_obj_set_width(ui_LightWhite, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_LightWhite, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_LightWhite, 110);
    lv_obj_set_y(ui_LightWhite, 0);
    lv_obj_set_align(ui_LightWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightWhite, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LightWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BulbWhite = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_BulbWhite, &ui_img_32356014);
    lv_obj_set_width(ui_BulbWhite, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_BulbWhite, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_align(ui_BulbWhite, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BulbWhite, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BulbWhite, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volumeTextWhite = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_volumeTextWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeTextWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumeTextWhite, -110);
    lv_obj_set_y(ui_volumeTextWhite, 35);
    lv_obj_set_align(ui_volumeTextWhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeTextWhite, "Volume");
    lv_obj_set_style_text_color(ui_volumeTextWhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volumeTextWhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeTextBlue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_volumeTextBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumeTextBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumeTextBlue, -110);
    lv_obj_set_y(ui_volumeTextBlue, 35);
    lv_obj_set_align(ui_volumeTextBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumeTextBlue, "Volume");
    lv_obj_add_flag(ui_volumeTextBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_volumeTextBlue, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_volumeTextBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightTextBlue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LightTextBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightTextBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightTextBlue, 110);
    lv_obj_set_y(ui_LightTextBlue, 35);
    lv_obj_set_align(ui_LightTextBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightTextBlue, "Light");
    lv_obj_add_flag(ui_LightTextBlue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_LightTextBlue, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightTextBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightTextWhite = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LightTextWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightTextWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightTextWhite, 110);
    lv_obj_set_y(ui_LightTextWhite, 35);
    lv_obj_set_align(ui_LightTextWhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightTextWhite, "Light");
    lv_obj_set_style_text_color(ui_LightTextWhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightTextWhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbTextWhite = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BulbTextWhite, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BulbTextWhite, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BulbTextWhite, 0);
    lv_obj_set_y(ui_BulbTextWhite, 35);
    lv_obj_set_align(ui_BulbTextWhite, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BulbTextWhite, "Temp");
    lv_obj_add_flag(ui_BulbTextWhite, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_BulbTextWhite, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BulbTextWhite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BulbTextBlue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BulbTextBlue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BulbTextBlue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BulbTextBlue, 0);
    lv_obj_set_y(ui_BulbTextBlue, 35);
    lv_obj_set_align(ui_BulbTextBlue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BulbTextBlue, "Bulb");
    lv_obj_set_style_text_color(ui_BulbTextBlue, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BulbTextBlue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LightBlue, ui_event_LightBlue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BulbBlue, ui_event_BulbBlue, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeBlue, ui_event_volumeBlue, LV_EVENT_ALL, NULL);

}
