// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: 1_69_round_display

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_1741863219, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightArc = lv_arc_create(ui_Screen4);
    lv_obj_set_width(ui_LightArc, 256);
    lv_obj_set_height(ui_LightArc, 256);
    lv_obj_set_align(ui_LightArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_LightArc, 100);
    lv_obj_set_style_arc_width(ui_LightArc, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LightArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_LightArc, &ui_img_bar_white_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_LightArc, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_LightArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_LightArc, &ui_img_bar_yellow_02_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_screen4RerutnBt = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_screen4RerutnBt, 80);
    lv_obj_set_height(ui_screen4RerutnBt, 40);
    lv_obj_set_x(ui_screen4RerutnBt, 0);
    lv_obj_set_y(ui_screen4RerutnBt, 110);
    lv_obj_set_align(ui_screen4RerutnBt, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_screen4RerutnBt, lv_color_hex(0x33DCFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen4RerutnBt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_screen4RerutnBt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_screen4RerutnBt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightReturnLabel = lv_label_create(ui_screen4RerutnBt);
    lv_obj_set_width(ui_LightReturnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightReturnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LightReturnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightReturnLabel, "Return");
    lv_obj_set_style_text_color(ui_LightReturnLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightReturnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightNum = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LightNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LightNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightNum, "50%");
    lv_obj_set_style_text_color(ui_LightNum, lv_color_hex(0xFFD400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightNum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabel = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightLabel, 0);
    lv_obj_set_y(ui_LightLabel, 50);
    lv_obj_set_align(ui_LightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabel, "Light");
    lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button15, 36);
    lv_obj_set_height(ui_Button15, 210);
    lv_obj_set_x(ui_Button15, -60);
    lv_obj_set_y(ui_Button15, 55);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button16, 36);
    lv_obj_set_height(ui_Button16, 210);
    lv_obj_set_x(ui_Button16, 60);
    lv_obj_set_y(ui_Button16, 55);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button19, 80);
    lv_obj_set_height(ui_Button19, 50);
    lv_obj_set_x(ui_Button19, 0);
    lv_obj_set_y(ui_Button19, 62);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button13, 80);
    lv_obj_set_height(ui_Button13, 40);
    lv_obj_set_x(ui_Button13, 0);
    lv_obj_set_y(ui_Button13, 153);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button14, 70);
    lv_obj_set_height(ui_Button14, 70);
    lv_obj_set_x(ui_Button14, -77);
    lv_obj_set_y(ui_Button14, 130);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button17 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button17, 70);
    lv_obj_set_height(ui_Button17, 70);
    lv_obj_set_x(ui_Button17, 77);
    lv_obj_set_y(ui_Button17, 130);
    lv_obj_set_align(ui_Button17, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightImage = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_LightImage, &ui_img_screen_brightness_45_white_png);
    lv_obj_set_width(ui_LightImage, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_LightImage, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_LightImage, 0);
    lv_obj_set_y(ui_LightImage, -70);
    lv_obj_set_align(ui_LightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_screen4RerutnBt, ui_event_screen4RerutnBt, LV_EVENT_ALL, NULL);

}
