// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: 1_46_round_display

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_LightArc;
extern void ui_event_screen4RerutnBt(lv_event_t * e);
extern lv_obj_t * ui_screen4RerutnBt;
extern lv_obj_t * ui_LightReturnLabel;
extern lv_obj_t * ui_LightNum;
extern lv_obj_t * ui_LightLabel;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_LightImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

